### ISSUE TITLE
Cache OOM

### ISSUE THREAD

**Issue by sempervictus** [guoqingbao/vllm.rs#357]
This shouldn't have _been_ a miss in the first place as its just an iteration added to a conversation but something got mis-aligned... Instead of an OOM it seems this should have forced release of all leaf nodes up to the KV space needed for the new request:

```rust
2026-05-23T18:57:25.814128Z  INFO vllm_rs::core::scheduler: GPU Kvcache: 43660 blocks (2794240 tokens) free, used 42.9% (24.00GB/55.98GB); CPU swap used 0.0% (0.00GB/111.96GB)
2026-05-23T18:57:25.814157Z  INFO vllm_rs::core::scheduler: GPU MambaState: 1 / 8 slots used (12.5%), approx 0.02GB/9.88GB (slot 18.42MB)
2026-05-23T18:58:17.598365Z  WARN vllm_rs::server::server: Tools enabled for request
2026-05-23T18:58:17.607061Z  INFO vllm_rs::server::server: Received completion request with 21 messages
2026-05-23T18:58:17.627722Z  INFO vllm_rs::core::block_manager: Prefix cache miss seq 198 (8127 tokens, 32768 cached blocks, raw_match=0 blocks)

thread 'main' (73) panicked at /root/.cargo/git/checkouts/cudarc-47fcf0f0d3baf3eb/bfb8f27/src/driver/safe/core.rs:293:26:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
```
although it says we were only using 42% of the KV space so we shouldn't have had to evict to add one more iter of that conversation to cache either. 🤷 

This appears to be an **internal** MM issue as device metrics show flat VRAM usage throughout the hours preceding the crash (~99% occupancy flat):

<img width="3793" height="259" alt="Image" src="https://github.com/user-attachments/assets/eb6c84b2-8cb1-4d59-b989-fe8cd92d30f7" />

**Comment by sempervictus** [comment]
Rebuilt on main with new binary name and still seeing the same effect on FP8 and FP4 models using BF16 or FP8 KVCache:
```rust
2026-05-23T20:58:59.909413Z  WARN xinfer::core::engine: [Stream] New request [Seq_id 15, 117679 tokens] received! (session_id: None)

2026-05-23T20:58:59.909503Z  INFO xinfer::server::parser: Tool parser selected: qwen_coder (model_id=nvidia/Qwen3.5-397B-A17B-NVFP4, enforce_parser=none)
2026-05-23T20:58:59.910728Z  INFO xinfer::core::block_manager: Prefix cache hit seq 15 (82944 cached tokens, 1296 blocks)
2026-05-23T20:58:59.937343Z  INFO xinfer::core::runner: Restored mamba prefix state for seq 15 (cached 82944 tokens)
2026-05-23T20:58:59.937455Z  INFO xinfer::core::runner: Restored mamba prefix state for seq 15 (cached 82944 tokens)
2026-05-23T20:58:59.938132Z  INFO xinfer::core::runner: Restored mamba prefix state for seq 15 (cached 82944 tokens)
2026-05-23T20:58:59.960626Z  INFO xinfer::core::runner: Restored mamba prefix state for seq 15 (cached 82944 tokens)
2026-05-23T20:58:59.986263Z ERROR xinfer::runner: Runner prefill error: Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: <candle_core::cuda_backend::device::CudaDevice as candle_core::backend::BackendDevice>::zeros_impl
   3: candle_core::device::Device::zeros
   4: candle_core::tensor::Tensor::zeros_impl
   5: attention_rs::moe::moe_gemm_nvfp4_hardware
   6: attention_rs::moe::moe_gemm_nvfp4
   7: xinfer::models::layers::moe::FusedMoeNvfp4::forward_with_routing
   8: xinfer::models::layers::moe::FusedMoeNvfp4::forward
   9: xinfer::models::qwen3_5_moe::Qwen3_5MoEDecoderLayer::forward
  10: xinfer::models::qwen3_5_moe::Qwen3_5MoEForCausalLM::forward_inner
  11: xinfer::models::qwen3_vl::Qwen3VLForConditionalGeneration::forward
  12: xinfer::core::runner::ModelRunner::run
  13: xinfer::runner::run_runner_process
  14: xinfer::main::{{closure}}
  15: tokio::runtime::park::CachedParkThread::block_on
  16: xinfer::main
  17: std::sys::backtrace::__rust_begin_short_backtrace
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal
  20: main
  21: <unknown>
  22: __libc_start_main
  23: _start
```

**Comment by guoqingbao** [comment]
> Rebuilt on main with new binary name and still seeing the same effect on FP8 and FP4 models using BF16 or FP8 KVCache:

Perhaps you may try prebuild binary, we didn't change the cache allocation logics in recent commits.

**Comment by sempervictus** [comment]
Yeah this is ... confusing - i went back several binaries and could reproduce it consistently and now i can't even on the newest one. Will keep an eye on it, the inconsistency makes me think some sort of data/async device action race?

**Comment by sempervictus** [comment]
@guoqingbao - _this_ may be of interest:
```rust

2026-05-24T03:24:29.013918Z  INFO xinfer::core::engine: Decoding: 1 active request(s) [Seq: [5]], avg. 47 tokens/s per request (total: 47 tokens/s)
2026-05-24T03:24:29.013949Z  INFO xinfer::core::scheduler: GPU Kvcache: 49455 blocks (3165120 tokens) free, used 8.1% (2.00GB/24.64GB); CPU swap used 0.0% (0.00GB/49.27GB)
2026-05-24T03:24:29.013962Z  INFO xinfer::core::scheduler: GPU MambaState: 1 / 8 slots used (12.5%), approx 0.04GB/4.35GB (slot 45.79MB)
2026-05-24T03:24:29.729143Z ERROR xinfer::runner: CaptureMambaPrefixState failed for seq 5 hash 11343161917569952933 preserve=false : Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: candle_core::cuda_backend::utils::Map1::map
   3: <candle_core::cuda_backend::CudaStorage as candle_core::backend::BackendStorage>::index_select
   4: candle_core::storage::Storage::index_select
   5: candle_core::tensor::Tensor::index_select
   6: attention_rs::mamba_cache::MambaCache::get_batch_recurrent_state
   7: attention_rs::mamba_cache::MambaCache::capture_prefix_state
   8: xinfer::models::qwen3_vl::Qwen3VLForConditionalGeneration::capture_mamba_prefix_state
   9: xinfer::core::runner::ModelRunner::capture_mamba_prefix_state
  10: xinfer::runner::run_runner_process
  11: xinfer::main::{{closure}}
  12: tokio::runtime::park::CachedParkThread::block_on
  13: xinfer::main
  14: std::sys::backtrace::__rust_begin_short_backtrace
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal
  17: main
  18: <unknown>
  19: __libc_start_main
  20: _start
```
the 397B seems to be the best reproducer for this and now its happening on mamba prefix state instead of kvalloc

**Comment by guoqingbao** [comment]
Found the root cause, will address this in the next version.

**Comment by guoqingbao** [comment]
Made some changes #360 The nvfp4 hardware path previously allocates large tensor buffers without memory pool.

**Comment by sempervictus** [comment]
@guoqingbao - unfortunatley still persists:
```rust

🛑 EXIT: Ctrl+C to quit. If unresponsive: Ctrl+P → Ctrl+Q (last resort).

2026-05-24T15:04:26.865868Z  WARN xinfer::core::engine: [Stream] New request [Seq_id 0, 60798 tokens] received! (session_id: None)

2026-05-24T15:04:26.866008Z  INFO xinfer::core::block_manager: Prefix cache miss seq 0 (60798 tokens, 0 cached blocks, raw_match=0 blocks)
2026-05-24T15:04:29.047577Z  INFO xinfer::core::runner: User's thinking preference for reasoning models: None
2026-05-24T15:04:29.047592Z  WARN xinfer::core::runner: Using user's sampling params: temp=Some(0.6), top_k=Some(20), top_p=Some(0.95), freq_penalty=None, pres_penalty=None
2026-05-24T15:04:29.065524Z  INFO xinfer::core::scheduler: Chunk prefilled 1 seq(s) [0:8192/60798] (8192 total tokens processed)
2026-05-24T15:04:31.155204Z  INFO xinfer::core::scheduler: Chunk prefilled 1 seq(s) [0:16384/60798] (16384 total tokens processed)
2026-05-24T15:04:33.309334Z  INFO xinfer::core::scheduler: Chunk prefilled 1 seq(s) [0:24576/60798] (24576 total tokens processed)
2026-05-24T15:04:35.542974Z  INFO xinfer::core::scheduler: Chunk prefilled 1 seq(s) [0:32768/60798] (32768 total tokens processed)
2026-05-24T15:04:37.830156Z  INFO xinfer::core::scheduler: Chunk prefilled 1 seq(s) [0:40960/60798] (40960 total tokens processed)
2026-05-24T15:04:37.998124Z ERROR xinfer::runner: Runner prefill error: Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: candle_core::cuda_backend::utils::Map2::map
   3: <candle_core::cuda_backend::CudaStorage as candle_core::backend::BackendStorage>::binary_impl
   4: candle_core::storage::Storage::binary_impl
   5: candle_core::tensor::Tensor::mul
   6: candle_core::tensor::Tensor::broadcast_mul
   7: xinfer::models::layers::moe::FusedMoeNvfp4::forward_with_routing
   8: xinfer::models::layers::moe::FusedMoeNvfp4::forward
   9: xinfer::models::qwen3_5_moe::Qwen3_5MoEDecoderLayer::forward
  10: xinfer::models::qwen3_5_moe::Qwen3_5MoEForCausalLM::forward_inner
  11: xinfer::models::qwen3_vl::Qwen3VLForConditionalGeneration::forward
  12: xinfer::core::runner::ModelRunner::run
  13: xinfer::runner::run_runner_process
  14: xinfer::main::{{closure}}
  15: tokio::runtime::park::CachedParkThread::block_on
  16: xinfer::main
  17: std::sys::backtrace::__rust_begin_short_backtrace
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal
  20: main
  21: <unknown>
  22: __libc_start_main
  23: _start
```

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) - unfortunatley still persists:

Is this only happen for nvfp4 hardware path?

**Comment by guoqingbao** [comment]
> > [@guoqingbao](https://github.com/guoqingbao) - unfortunatley still persists:
> 
> Is this only happen for nvfp4 hardware path?

I'm not sure if you are using the latest code, but we have latest prebuild binaries working on different platforms:

```
curl -sSL https://guoqingbao.github.io/xinfer/install.sh | bash
```

**Comment by sempervictus** [comment]
I do, pulled from main, rebuilt in the dockers, have a docker now which does the pip install too. This is happening on the 397 fp4 model very consistently but the 122 fp8 and 80b fp8/fp4 seem mostly fine on 4xSM120. I can reproduce in the sm121 occasionally with the 80b fp4 but that may be due to the varbuilder problem limiting the usable "vram" in shared memory

**Comment by guoqingbao** [comment]
> I do, pulled from main, rebuilt in the dockers, have a docker now which does the pip install too. This is happening on the 397 fp4 model very consistently but the 122 fp8 and 80b fp8/fp4 seem mostly fine on 4xSM120. I can reproduce in the sm121 occasionally with the 80b fp4 but that may be due to the varbuilder problem limiting the usable "vram" in shared memory

You may lower the kv-fraction since the 397B prefill requires significantlly large intermediate buffers in addition to kvcache.

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) - unfortunatley still persists:

Do you have full log of this, I think the OOM is the intermediate buffer issue, where the 397B model prefill requires significantly large buffers than expected.

**Comment by guoqingbao** [comment]
> > [@guoqingbao](https://github.com/guoqingbao) - unfortunatley still persists:
> 
> Do you have full log of this, I think the OOM is the intermediate buffer issue, where the 397B model prefill requires significantly large buffers than expected.

This can be mitigated also by reducing the prefill chunk size, which is 8K by default.

**Comment by sempervictus** [comment]
> This can be mitigated also by reducing the prefill chunk size, which is 8K by default.

About that: any thoughts on dynamic chunk sizing to optimize for prefill rates/available memory?

> You may lower the kv-fraction since the 397B prefill requires significantlly large intermediate buffers in addition to kvcache.

Can't supply both `--kv-fraction` and `--max-model-len` while the latter is needed when using dynamic YARN scaling _unless_ you want me to amend the scaling logic to **auto-multiply** the context window to the closest value to the `--kv-fraction` space divided by the `--max-num-seqs` set if that's used instead of `--max-model-len` 😄

**Comment by guoqingbao** [comment]
> > This can be mitigated also by reducing the prefill chunk size, which is 8K by default.
> 
> About that: any thoughts on dynamic chunk sizing to optimize for prefill rates/available memory?
> 
> > You may lower the kv-fraction since the 397B prefill requires significantlly large intermediate buffers in addition to kvcache.
> 
> Can't supply both `--kv-fraction` and `--max-model-len` while the latter is needed when using dynamic YARN scaling _unless_ you want me to amend the scaling logic to **auto-multiply** the context window to the closest value to the `--kv-fraction` space divided by the `--max-num-seqs` set if that's used instead of `--max-model-len` 😄

You may try this #361

**Comment by guoqingbao** [comment]
> ARN scaling _unless_ you want me to amend the scaling logic to **auto-multiply**

We have yarn scaling factor argument.

**Comment by sempervictus** [comment]
We do but it doesn't automatically extend maxmodellen

**Comment by sempervictus** [comment]
Can reproduce with MiniMax2.7 as well - trying to get q/k norm working and ran into:
```rust
2026-05-27T03:01:59.141845Z  INFO xinfer::core::engine: Prefilling 1 seq(s) [0]: 46 total tokens in 0.12s (386.55 tokens/s)
2026-05-27T03:02:01.889398Z  INFO xinfer::core::block_manager: Prefix cache insert seq 0 (252 tokens, 3 blocks)
2026-05-27T03:02:01.889599Z  INFO xinfer::core::scheduler: GPU Kvcache: 28369 blocks (1815616 tokens) free, used 0.0% (0.01GB/53.68GB); CPU swap used 0.0% (0.00GB/107.36GB)
2026-05-27T03:02:01.889626Z  WARN xinfer::server::server: --- Performance Metrics ---
2026-05-27T03:02:01.889648Z  INFO xinfer::server::server: [1 requests] ⏱️ Prompt tokens: 45 in 0.12s (378.15 t/s)
2026-05-27T03:02:01.889658Z  INFO xinfer::server::server: [1 requests] ⏱️ Decoded tokens: 207 in 2.75s (75.33 t/s)
2026-05-27T03:03:45.045816Z  INFO xinfer::utils::guidance_grammar: [llg] Chat template contains reasoning tokens, no fallback needed
2026-05-27T03:03:45.080314Z  WARN xinfer::core::engine: [Stream] New request [Seq_id 1, 6863 tokens] received! (session_id: None)

2026-05-27T03:03:45.080407Z  INFO xinfer::core::block_manager: Prefix cache miss seq 1 (6863 tokens, 3 cached blocks, raw_match=0 blocks)
2026-05-27T03:03:45.096397Z ERROR xinfer::runner: Runner prefill error: Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: <candle_core::cuda_backend::device::CudaDevice as candle_core::backend::BackendDevice>::zeros_impl
   3: candle_core::device::Device::zeros
   4: candle_core::tensor::Tensor::zeros_impl
   5: attention_rs::moe::moe_gemm_nvfp4_hardware
   6: attention_rs::moe::moe_gemm_nvfp4
   7: xinfer::models::layers::moe::FusedMoeNvfp4::forward_with_routing
   8: xinfer::models::layers::moe::FusedMoeNvfp4::forward
   9: xinfer::models::minimax::MiniMaxDecoderLayer::forward
  10: xinfer::models::minimax::MiniMaxForCausalLM::forward_inner
  11: xinfer::core::runner::ModelRunner::run
  12: xinfer::runner::run_runner_process
  13: xinfer::main::{{closure}}
  14: tokio::runtime::park::CachedParkThread::block_on
  15: xinfer::main
  16: std::sys::backtrace::__rust_begin_short_backtrace
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal
  19: main
  20: <unknown>
  21: __libc_start_main
  22: _start
```
that's w/ fp8 kvcache too and just the project ReadMe.md set this off :-\\ 

Seems to be the same stacktrace

**Comment by sempervictus** [comment]
Well, its not the `--max-model-len` - turns out that dropping that value by 50% produces a **new** crash stack which still OOMs GPUs:
```rust
2026-05-27T03:11:18.137992Z  WARN xinfer::core::engine: [Stream] New request [Seq_id 0, 6863 tokens] received! (session_id: None)

2026-05-27T03:11:18.138090Z  INFO xinfer::core::block_manager: Prefix cache miss seq 0 (6863 tokens, 0 cached blocks, raw_match=0 blocks)
2026-05-27T03:11:18.265898Z ERROR xinfer::runner: Runner prefill error: Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: std::thread::local::LocalKey<T>::with
   3: attention_rs::workspace::cuda::get_moe_activation_pool
   4: attention_rs::moe::moe_gemm_nvfp4_hardware
   5: attention_rs::moe::moe_gemm_nvfp4
   6: xinfer::models::layers::moe::FusedMoeNvfp4::forward_with_routing
   7: xinfer::models::layers::moe::FusedMoeNvfp4::forward
   8: xinfer::models::minimax::MiniMaxDecoderLayer::forward
   9: xinfer::models::minimax::MiniMaxForCausalLM::forward_inner
  10: xinfer::core::runner::ModelRunner::run
  11: xinfer::runner::run_runner_process
  12: xinfer::main::{{closure}}
  13: tokio::runtime::park::CachedParkThread::block_on
  14: xinfer::main
  15: std::sys::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
)
```
have enough VRAM to run that thing as FP8, getting one of those models pulled down so i can see if this is NVFP4-specific but looks like `attention_rs::workspace::cuda::get_moe_activation_pool` might be a candidate for culprit status since its an MM function...

**Comment by guoqingbao** [comment]
> Well, its not the `--max-model-len` - turns out that dropping that value by 50% produces a **new** crash stack which still OOMs GPUs:

You are able run with default parameter without max-model-len and max-num_seqs, the program will reseve sufficient vram for runtime usage.

**Comment by sempervictus** [comment]
Seems like that should happen even with extended model lengths - default max embeddings is only ~200k (although it goes nuts well before then which is what i'm trying to figure out re q/k normalization) :-(

**Comment by guoqingbao** [comment]
> Seems like that should happen even with extended model lengths - default max embeddings is only ~200k (although it goes nuts well before then which is what i'm trying to figure out re q/k normalization) :-(

This is related to bf16 weight loaded as F16, some precision loss especially in the gdn layers.

**Comment by sempervictus** [comment]
Oh the fp4 stuff on multi rank goes nuts on hardware path too - all the big models I hoped to run on the Blackwells collapse into loops while the fp8s go to kV space limitations. Your theory about block scale loading seems very viable but so far everything I've seen assigns to the same rank for scales and blocks.

**Comment by sempervictus** [comment]
@guoqingbao  - unfortunately still hitting this with #373 on the 397B NVFP4 running on 4xRTX6000PRO cards (96GB per card) at a mere 130k tokens of input even with `--prefill-chunk-size 1024`:

```rust
2026-06-01T23:51:26.501818Z  INFO xinfer::core::block_manager: Prefix cache miss seq 15 (130161 tokens, 156 cached blocks, raw_match=0 blocks)
2026-06-01T23:51:26.501831Z  INFO xinfer::server::parser: Tool parser selected: qwen_coder (model_id=nvidia/Qwen3.5-397B-A17B-NVFP4, enforce_parser=none)
2026-06-01T23:51:26.569960Z ERROR xinfer::runner: Runner prefill error: Err(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: std::thread::local::LocalKey<T>::with
   3: attention_rs::workspace::cuda::get_moe_activation_pool
   4: attention_rs::moe::moe_gemm_nvfp4_hardware
   5: attention_rs::moe::moe_gemm_nvfp4
   6: xinfer::models::layers::moe::FusedMoeNvfp4::forward_with_routing
   7: xinfer::models::layers::moe::FusedMoeNvfp4::forward
   8: xinfer::models::qwen3_5_moe::Qwen3_5MoEDecoderLayer::forward
   9: xinfer::models::qwen3_5_moe::Qwen3_5MoEForCausalLM::forward_inner
  10: xinfer::models::qwen3_vl::Qwen3VLForConditionalGeneration::forward
  11: xinfer::core::runner::ModelRunner::run
  12: xinfer::runner::run_runner_process
  13: xinfer::main::{{closure}}
  14: tokio::runtime::park::CachedParkThread::block_on
  15: xinfer::main
  16: std::sys::backtrace::__rust_begin_short_backtrace
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal
  19: main
  20: <unknown>
  21: __libc_start_main
  22: _start

```

**Comment by guoqingbao** [comment]
Can we close this, is #377 solved this issue?

**Comment by sempervictus** [comment]
Apologies, thought i had.
